# Autogenerated wrapper script for systemd_jll for armv7l-linux-gnueabihf
export libsystemd, libudev

using libcap_jll
using Libgcrypt_jll
using P11Kit_jll
using Lz4_jll
using XZ_jll
using Zstd_jll
using Libmount_jll
JLLWrappers.@generate_wrapper_header("systemd")
JLLWrappers.@declare_library_product(libsystemd, "libsystemd.so.0")
JLLWrappers.@declare_library_product(libudev, "libudev.so.1")
function __init__()
    JLLWrappers.@generate_init_header(libcap_jll, Libgcrypt_jll, P11Kit_jll, Lz4_jll, XZ_jll, Zstd_jll, Libmount_jll)
    JLLWrappers.@init_library_product(
        libsystemd,
        "lib/libsystemd.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libudev,
        "lib/libudev.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
